import test from 'node:test';
import assert from 'node:assert/strict';
import '../public/src/extra-data.js';
import '../public/src/expansion-data.js';
import '../public/src/paper-data.js';
import {Inventory,RECIPES,matchRecipe,craft,SMELTING} from '../public/src/core.js';
import {workerCount,renderSize,cleanOptions,frameInterval} from '../public/src/graphics-options.js';
import {cropAge,hydrated,pickupReady} from '../public/src/farming.js';
test('75% worker allocation keeps a minimum of one worker',()=>{for(const [threads,n]of [[1,1],[2,1],[4,3],[8,6],[16,12],[undefined,1]])assert.equal(workerCount(threads),n);});
test('resolution budgets preserve screen aspect and device limits',()=>{assert.deepEqual(renderSize('1920x1080',1920,1080),[1920,1080]);assert.deepEqual(renderSize('1920x1080',1000,1000),[1080,1080]);const [w,h]=renderSize('3840x2160',1920,1080,2048);assert.equal(w,2048);assert.equal(h,1152);});
test('settings discard unknown fields and clamp expensive controls',()=>{const options=cleanOptions({maxLights:999,renderDistance:200,aa:'fake',resolution:'99999x99999',token:'secret',smoothLighting:false});assert.equal(options.maxLights,128);assert.equal(options.renderDistance,12);assert.equal(options.aa,'none');assert.equal(options.smoothLighting,false);assert.equal('token'in options,false);assert.equal(cleanOptions({maxLights:0}).maxLights,2);});
test('inactive rendering reduces frame rate while active play stays uncapped',()=>{assert.equal(frameInterval({}),0);assert.equal(frameInterval({focused:false}),100);assert.equal(frameInterval({hidden:true}),1000);assert.equal(frameInterval({menu:true}),33);});
test('farmland water within five blocks increases crop growth by exactly 15%',()=>{const cells=new Map([['0,9,0',25],['0,10,0',26],['5,9,0',14]]),world={get:(x,y,z)=>cells.get(`${x},${y},${z}`)||0,metadata:new Map([['0,10,0',{updated_at:new Date(100000).toISOString()}]])},clock={serverMs:()=>200000};assert.equal(hydrated(world,0,10,0),true);assert.ok(Math.abs(cropAge(world,clock,0,10,0)-115)<.001);cells.delete('5,9,0');cells.set('5,9,1',14);assert.equal(cropAge(world,clock,0,10,0),100);cells.set('0,9,0',2);cells.set('1,9,0',14);assert.equal(hydrated(world,0,10,0),false);});
test('player-thrown drops require two seconds, ordinary drops retain 650ms',()=>{const row={created_at:new Date(1000).toISOString(),player_dropped:true};assert.equal(pickupReady(row,2999),false);assert.equal(pickupReady(row,3000),true);assert.equal(pickupReady({...row,player_dropped:false},1650),true);});
test('one bone crafts three bone meal and deepslate smelts into placeable lava',()=>{const r=RECIPES.find(r=>r.out==='bone_meal');assert.equal(matchRecipe([{id:'bone',count:1},null,null,null],2),r);const inv=new Inventory;inv.add('bone',1);assert.equal(craft(inv,r),true);assert.equal(inv.count('bone'),0);assert.equal(inv.count('bone_meal'),3);assert.equal(SMELTING.deepslate,'lava');});
